@local=http://localhost:8000

@uat=https://diogenes-pwhb.koyeb.app

@prefix=api/v1

@collections=configs


###
GET {{local}}/{{prefix}}/{{collections}}


###
GET {{local}}/{{prefix}}/{{collections}}/65198dca2d0f9fbd0a2d0b3f

###
POST {{local}}/{{prefix}}/{{collections}}
Content-Type: application/json

{
    "name": "auth",
    "register": {
        "default": {
            "active": true,
            "role": "player"
        }
    }
}

###
PATCH {{local}}/{{prefix}}/{{collections}}/6495160c183665ad2f629e5c
Content-Type: application/json

{
    "name": "backend"
}


###
PUT {{local}}/{{prefix}}/{{collections}}/65198dca2d0f9fbd0a2d0b3f
Content-Type: application/json

{
    "hello": "world"
}


###
DELETE {{local}}/{{prefix}}/{{collections}}/6519900bd3cea317a658af32

